from typing import Protocol


class Logger(Protocol):
    def info(self, message: str) -> None: ...
    def warning(self, message: str) -> None: ...
    def error(self, message: str, exc_info: bool = False) -> None: ...
    def debug(self, message: str) -> None: ...